# Generated by Django 4.2.2 on 2023-11-18 07:28

from django.db import migrations, models
import reservation.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_customuser_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUserApiList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            bases=(reservation.mixins.CustomLoginRequiredMixin, reservation.mixins.CustomAuthorizationMixin, models.Model),
        ),
    ]
