# Generated by Django 4.2.2 on 2023-06-30 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_alter_reservation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='lname',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
