# Generated by Django 4.2.2 on 2023-07-03 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_alter_platform_user_apartment_reservation_apartment'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_date', models.DateField()),
                ('vat_rate', models.DecimalField(decimal_places=2, default=7, max_digits=5)),
                ('citytax_rate', models.DecimalField(decimal_places=2, default=5, max_digits=5)),
            ],
            options={
                'ordering': ['-starting_date'],
            },
        ),
    ]
