# Generated by Django 4.2.2 on 2023-07-05 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0007_taxrate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taxrate',
            options={'ordering': ['-start_date']},
        ),
        migrations.RenameField(
            model_name='taxrate',
            old_name='starting_date',
            new_name='start_date',
        ),
        migrations.AlterField(
            model_name='platform',
            name='address',
            field=models.CharField(blank=True, default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='platform',
            name='kundennummer',
            field=models.CharField(blank=True, default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='platform',
            name='login',
            field=models.CharField(blank=True, default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='platform',
            name='name',
            field=models.CharField(blank=True, default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='platform',
            name='tel',
            field=models.CharField(blank=True, default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='apartment',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='reservation.apartment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='lname',
            field=models.CharField(blank=True, default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='platform',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='reservation.platform'),
            preserve_default=False,
        ),
    ]
