# Generated by Django 4.2.2 on 2023-07-13 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0009_reservation_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='nationality',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
