# Generated by Django 4.2.2 on 2023-07-14 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0011_taxrate_tax_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxrate',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
