# Generated by Django 4.2.2 on 2023-07-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservation", "0013_invoice"),
    ]

    operations = [
        migrations.AddField(
            model_name="taxrate",
            name="full_vat_rate",
            field=models.DecimalField(decimal_places=2, default=12, max_digits=5),
        ),
    ]
