# Generated by Django 4.2.2 on 2023-07-18 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0013_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='reservation',
            field=models.ForeignKey(default=111, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='reservation.reservation'),
            preserve_default=False,
        ),
    ]
