# Generated by Django 4.2.2 on 2023-07-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0014_invoice_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_netto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
