# Generated by Django 4.2.2 on 2023-07-18 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0016_invoice_invoice_citytax_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='number_of_guests',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
