# Generated by Django 4.2.2 on 2023-07-18 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0017_reservation_number_of_guests'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
