# Generated by Django 4.2.2 on 2023-10-08 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservation', '0023_alter_reservation_apartment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='end_date',
            field=models.DateField(blank=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='number_of_guests',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='reservation.platform'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='purpose',
            field=models.CharField(blank=True, choices=[('holiday', 'holiday'), ('business', 'business'), ('no-show', 'no-show')], default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='rech_num',
            field=models.CharField(blank=True, default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_date',
            field=models.DateField(blank=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='t_sum',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
